# Form implementation generated from reading ui file 'c:\Users\Harsue\Desktop\CODIGOS\FRIKIZONE\CODIGO\interfaz_ui\interfaz_principal.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("*{\n"
"    font-size: 12px;\n"
"    font-family: Sylfaen;\n"
"}\n"
"\n"
"#centralwidget{background: url(\"images/fondo.png\")}\n"
"#contenedor_principal{\n"
"    background: rgba(0,0,0,200)\n"
"}\n"
"\n"
"#widget_lateral QPushButton{\n"
"    border: none;\n"
"    border-bottom: 1px solid rgb(220, 253, 255);\n"
"    width: 100%;\n"
"    padding: 1em 8px;\n"
"}\n"
"\n"
"#stacked_widget QWidget{\n"
"    background: rgba(0,0,0,200);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.contenedor_principal = QtWidgets.QWidget(parent=self.centralwidget)
        self.contenedor_principal.setObjectName("contenedor_principal")
        self.contenedor_widgets = QtWidgets.QGridLayout(self.contenedor_principal)
        self.contenedor_widgets.setObjectName("contenedor_widgets")
        self.widget_superior = QtWidgets.QWidget(parent=self.contenedor_principal)
        self.widget_superior.setObjectName("widget_superior")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_superior)
        self.horizontalLayout.setContentsMargins(1, -1, 30, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
