# Form implementation generated from reading ui file 'c:\Users\Harsue\Desktop\CODIGOS\FRIKIZONE\CODIGO\interfaz_ui\ventana4.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 500)
        MainWindow.setMinimumSize(QtCore.QSize(500, 500))
        MainWindow.setMaximumSize(QtCore.QSize(500, 500))
        MainWindow.setStyleSheet("QWidget#centralwidget{\n"
"background: qlineargradient(spread:pad, x1:0.517, y1:0, x2:0.511, y2:1, stop:0 rgba(20, 20, 02, 100), stop:1 rgba(12, 38, 60, 1))\n"
"}\n"
"\n"
"\n"
"QFrame{\n"
"    background-color:transparent;\n"
"    border:none;\n"
"}\n"
"\n"
"QlineEdit{\n"
"    background:red;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setStyleSheet("font: 20pt \"Sylfaen\";\n"
"color:rgb(85, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(300, 0))
        self.frame.setMaximumSize(QtCore.QSize(200, 100))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setMaximumSize(QtCore.QSize(200, 50))
        self.label_2.setStyleSheet("QLabel{\n"
"    color:rgba(85, 255, 255,1)\n"
"}\n"
"")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"    color:rgb(85, 255, 255);\n"
"    background:rgba(10,12,30,0.8);\n"
"    border-style:none;\n"
"    border-radius:8px\n"
"}\n"
"")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_2.addWidget(self.lineEdit)
        self.verticalLayout.addWidget(self.frame)
        self.frame_6 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_6.setMinimumSize(QtCore.QSize(300, 0))
        self.frame_6.setMaximumSize(QtCore.QSize(200, 100))
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_5 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_5.setMaximumSize(QtCore.QSize(200, 50))
        self.label_5.setStyleSheet("QLabel{\n"
"    color:rgb(85, 255, 255)\n"
"}\n"
"")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_7.addWidget(self.label_5)
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.frame_6)
        self.lineEdit_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEdit_2.setStyleSheet("QLineEdit{\n"
"    color:rgb(85, 255, 255);\n"
"    background:rgba(10,12,30,0.8);\n"
"    border-style:none;\n"
"    border-radius:8px\n"
"}\n"
"")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_7.addWidget(self.lineEdit_2)
        self.verticalLayout.addWidget(self.frame_6)
        self.frame_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_2.setMinimumSize(QtCore.QSize(300, 0))
        self.frame_2.setMaximumSize(QtCore.QSize(200, 100))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(parent=self.frame_2)
        self.label.setMaximumSize(QtCore.QSize(200, 50))
        self.label.setStyleSheet("QLabel{\n"
"    color:rgb(85, 255, 255)\n"
"}\n"
"")
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.frame_2)
        self.lineEdit_3.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEdit_3.setStyleSheet("QLineEdit{\n"
"    color:rgb(85, 255, 255);\n"
"    background:rgba(10,12,30,0.8);\n"
"    border-style:none;\n"
"    border-radius:8px\n"
"}\n"
"")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_3.addWidget(self.lineEdit_3)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_5 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_5.setMinimumSize(QtCore.QSize(300, 0))
        self.frame_5.setMaximumSize(QtCore.QSize(200, 100))
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_4 = QtWidgets.QLabel(parent=self.frame_5)
        self.label_4.setMaximumSize(QtCore.QSize(200, 50))
        self.label_4.setStyleSheet("QLabel{\n"
"    color:rgb(85, 255, 255)\n"
"}\n"
"")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_6.addWidget(self.label_4)
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=self.frame_5)
        self.lineEdit_4.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEdit_4.setStyleSheet("QLineEdit{\n"
"    color:rgb(85, 255, 255);\n"
"    background:rgba(10,12,30,0.8);\n"
"    border-style:none;\n"
"    border-radius:8px\n"
"}\n"
"")
        self.lineEdit_4.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_6.addWidget(self.lineEdit_4)
        self.verticalLayout.addWidget(self.frame_5)
        self.frame_3 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_3.setMinimumSize(QtCore.QSize(300, 0))
        self.frame_3.setMaximumSize(QtCore.QSize(200, 100))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_3.setMaximumSize(QtCore.QSize(200, 50))
        self.label_3.setStyleSheet("QLabel{\n"
"    color:rgb(85, 255, 255)\n"
"}\n"
"")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.lineEdit_5 = QtWidgets.QLineEdit(parent=self.frame_3)
        self.lineEdit_5.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEdit_5.setStyleSheet("QLineEdit{\n"
"    color:rgb(85, 255, 255);\n"
"    background:rgba(10,12,30,0.8);\n"
"    border-style:none;\n"
"    border-radius:8px\n"
"}\n"
"")
        self.lineEdit_5.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout_4.addWidget(self.lineEdit_5)
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_4.setMinimumSize(QtCore.QSize(100, 0))
        self.frame_4.setMaximumSize(QtCore.QSize(100, 50))
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pushButton = QtWidgets.QPushButton(parent=self.frame_4)
        self.pushButton.setMaximumSize(QtCore.QSize(100, 30))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    border-radius:10px;\n"
"    color: white;\n"
"    background-color: rgba(57, 215, 200,0.8);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(57, 225, 180,0.8);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgba(57, 210, 168,0.8);\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_5.addWidget(self.pushButton)
        self.verticalLayout.addWidget(self.frame_4)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:700;\">REGISTRO DE USUARIO</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "Nombre (Usuario)"))
        self.label_5.setText(_translate("MainWindow", "Cédula"))
        self.label.setText(_translate("MainWindow", "Teléfono"))
        self.label_4.setText(_translate("MainWindow", "Contraseña"))
        self.label_3.setText(_translate("MainWindow", "Confirmar Contraseña"))
        self.pushButton.setText(_translate("MainWindow", "REGISTRAR"))
